<a href="https://colab.research.google.com/github/abbadad/3mtt-Week-2-Assignment/blob/main/3mtt_Week_5_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment**:
Use Pandas to clean and preprocess a messy dataset, documenting the steps taken during the cleaning process.

In [ ]:
# Steps of Preprocessing of Data
# 1. Import Necessary Liberary
# 2. Read Data Set
# 3. Sanity Check of Data
# 4. Exploratory Data Analysis
# 5. Missing Value Treatment
# 6. Outliers Treatment
# 7. Duplicate and Gabage Value Treatment

**Import Necessary Libery**

In [ ]:
import pandas as pd

**Read Dataset**

In [10]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [7]:
import pandas as pd

In [15]:
path= '/content/drive/MyDrive/Lab Inventory.csv'
df= pd.read_csv(path)
df.head()

,ID,Name,Description,Unit price,Quantity \nin stock,Inventory value,Reorder level,Reorder time in days,Quantity \nin reorder,Discontinued?
0,IN0001,Item 1,Desc 1,$51.00,25,#VALUE!,29,13,50,NaN
1,IN0002,Item 2,Desc 2,$93.00,132,#VALUE!,231,4,50,NaN
2,IN0003,Item 3,Desc 3,$57.00,151,NaN,114,11,150,NaN
3,IN0004,Item 4,Desc 4,$19.00,186,NaN,158,6,50,NaN
4,IN0005,Item 5,Desc 5,$75.00,62,"$1,275",39,12,50,NaN

In [16]:
df.tail()

,ID,Name,Description,Unit price,Quantity \nin stock,Inventory value,Reorder level,Reorder time in days,Quantity \nin reorder,Discontinued?
20,IN0021,Item 21,Desc 21,$19.00,112,"$5,529",75,11,50,NaN
21,IN0022,Item 22,Desc 22,$24.00,182,$72,132,15,150,NaN
22,IN0023,Item 23,Desc 23,$29.00,106,"$11,726",142,1,150,Yes
23,IN0024,Item 24,Desc 24,$75.00,173,"$1,984",127,9,100,NaN
24,IN0025,Item 25,Desc 25,$14.00,28,"$2,128",21,8,50,NaN

**Sanity Check of Data**

In [18]:
# Shape
df.shape

(25, 10)

In [19]:
# Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0    ID                   25 non-null     object
 1   Name                  25 non-null     object
 2   Description           25 non-null     object
 3   Unit price            25 non-null     object
 4   Quantity
in stock    25 non-null     int64
 5   Inventory value       23 non-null     object
 6   Reorder level         25 non-null     int64
 7   Reorder time in days  25 non-null     int64
 8   Quantity
in reorder  25 non-null     int64
 9   Discontinued?         3 non-null      object
dtypes: int64(4), object(6)
memory usage: 2.1+ KB

In [21]:
# Finding Missing Value
df.isnull().sum()

 ID                       0
Name                      0
Description               0
Unit price                0
Quantity \nin stock       0
Inventory value           2
Reorder level             0
Reorder time in days      0
Quantity \nin reorder     0
Discontinued?            22
dtype: int64

In [23]:
# Finding Duplicate
df.duplicated().sum()

0

In [27]:
# Identifying Garbage value
for i in df.select_dtypes(include="object").columns:
  print(df[i].value_counts())
  print("***"*10)

IN0001    1
IN0014    1
IN0024    1
IN0023    1
IN0022    1
IN0021    1
IN0020    1
IN0019    1
IN0018    1
IN0017    1
IN0016    1
IN0015    1
IN0013    1
IN0002    1
IN0012    1
IN0011    1
IN0010    1
IN0009    1
IN0008    1
IN0007    1
IN0006    1
IN0005    1
IN0004    1
IN0003    1
IN0025    1
Name:  ID, dtype: int64
******************************
Item 1     1
Item 14    1
Item 24    1
Item 23    1
Item 22    1
Item 21    1
Item 20    1
Item 19    1
Item 18    1
Item 17    1
Item 16    1
Item 15    1
Item 13    1
Item 2     1
Item 12    1
Item 11    1
Item 10    1
Item 9     1
Item 8     1
Item 7     1
Item 6     1
Item 5     1
Item 4     1
Item 3     1
Item 25    1
Name: Name, dtype: int64
******************************
Desc 1     1
Desc 14    1
Desc 24    1
Desc 23    1
Desc 22    1
Desc 21    1
Desc 20    1
Desc 19    1
Desc 18    1
Desc 17    1
Desc 16    1
Desc 15    1
Desc 13    1
Desc 2     1
Desc 12    1
Desc 11    1
Desc 10    1
Desc 9     1
Desc 8     1
Desc 7     1
Desc 6     1
Desc 5     1
Desc 4     1
Desc 3     1
Desc 25    1
Name: Description, dtype: int64
******************************
$19.00    2
$75.00    2
$59.00    2
$51.00    1
$32.00    1
$29.00    1
$24.00    1
$16.00    1
$82.00    1
$12.00    1
$97.00    1
$90.00    1
$26.00    1
$42.00    1
$93.00    1
$18.00    1
$50.00    1
$38.00    1
$56.00    1
$11.00    1
$57.00    1
$14.00    1
Name: Unit price, dtype: int64
******************************
#VALUE!    2
$1,275     1
$1,984     1
$11,726    1
$72        1
$5,529     1
$8,640     1
$1,472     1
$2,604     1
$1,872     1
$396       1
$10,384    1
$8,750     1
$7,198     1
$3,838     1
$3,248     1
$55        1
$4,650     1
$3,534     1
$8,607     1
$12,276    1
$2,128     1
Name: Inventory value, dtype: int64
******************************
Yes    3
Name: Discontinued?, dtype: int64
******************************